server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
    datasource:
      url: jdbc:mysql://wemeetnowdb.chmy408yifq6.ap-northeast-2.rds.amazonaws.com:3306/minjudb?useSSL=false&serverTimezone=Asia/Seoul
      username: minjooig
      password: wanduek3612
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    aws:
      s3:
        bucket: ${cloud.aws.s3.bucket}
      credentials:
        accessKey: ${cloud.aws.s3.credentials.access-key}
        secretKey: ${cloud.aws.s3.credentials.secret-key}
      region:
        static: ${cloud.aws.s3.region.static}
      stack:
        auto: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client.id}
            client-secret: ${kakao.client.secret}
            redirect-uri: ${kakao.redirect.url}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gathering?serverTimezone=Asia/Seoul
    username: ${MYSQL_NAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      port: 6379
      host: 127.0.0.1

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

admin:
  token: ${ADMIN_TOKEN}


