server:
  port: 8080

spring:
  jwt:
    secret:
      key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg\\=\\=

  cloud:
    aws:
      s3:
        bucket: ${cloud.aws.s3.bucket}
      credentials:
        accessKey: ${cloud.aws.s3.credentials.access-key}
        secretKey: ${cloud.aws.s3.credentials.secret-key}
      region:
        static: ${cloud.aws.s3.region.static}
      stack:
        auto: false

  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gathering?serverTimezone=Asia/Seoul
    username: ${MYSQL_NAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      port: 6379
      host: 127.0.0.1

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

