spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        auto_quote_keyword: true
        highlight_sql: true
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

cloud:
  aws:
    s3:
      bucket: ${cloud.aws.s3.bucket}
    credentials:
      accessKey: ${cloud.aws.s3.credentials.access-key}
      secretKey: ${cloud.aws.s3.credentials.secret-key}
    region:
      static: ${cloud.aws.s3.region.static}
    stack:
      auto: false