server:
  port: 8080
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DB_NAME}?serverTimezone=Asia/Seoul
    username: ${MYSQL_NAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      port: 6379
      host: 127.0.0.1

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET}
      credentials:
        accessKey: ${S3_PUBLIC}
        secretKey: ${S3_SECRET}
      region:
        static: ${S3_REGION}
      stack:
        auto: false


jwt:
  secret:
    key: ${JWT_SECRET_KEY}

